[tool.ariadne-codegen]
remote_schema_url = "https://api.github.com/graphql"
remote_schema_headers = { Authorization = "$GITHUB_TOKEN" }
remote_schema_timeout = 30
remote_schema_verify_ssl = true
target_file_path = "src/planpilot/core/providers/github/schema.graphql"
plugins = []
